### ISSUE TITLE
Didn't combine reducers

### ISSUE THREAD

**Issue by simba0808** [BlueOcean5911/Floz_front-end#1]
In /store/reducers/index.ts, you didn't combine any reducers.

// ==============================|| COMBINE REDUCERS ||============================== //

const reducers = combineReducers({
  
});

**Comment by BlueOcean5911** [comment]
ok, but this code is in development.  I will use persist redux to store state variables.
What do you think which one is better between persist redux and zustand.

**Comment by simba0808** [comment]
-Redux is powerful, but its power comes with complexity. 
  It requires setting up actions, reducers, and stores, which can be overwhelming for beginners. 
-Zustand, on the other hand, takes a minimalistic approach. 
  It’s a single hook that provides state management without the need for a complex setup. 
  This simplicity makes Zustand more accessible, especially for smaller projects or developers new to state management.
Ultimately, the choice between Zustand and Redux should be based on the specific needs and constraints of your project.

I wish this is helpful for you.
